
# NumPy Notebook

## Introduction to NumPy

NumPy is one of the main Python libraries used for numerical computing. It provides support for creating scalars, vectors, matrices, and tensors. NumPy also enables performing linear algebra, element-wise operations, statistical analysis, and data manipulation.



In [ ]:
!pip install numpy -q

In [ ]:
import numpy as np

### Creating Scalars, Vectors, Matrices, and Tensors

In [ ]:
#array
sc = np.array(5)
print(sc)
sc.shape
#integer
a = 5
print(5)

5
5


In [ ]:
# Scalar: A single digit value
scalar = np.array(10)
print('Scalar:', scalar)
print('Shape:', scalar.shape)
scalar.dtype


Scalar: 10
Shape: ()


dtype('int64')

In [ ]:

# Vector: A one-dimensional sequence of numbers
vector = np.array([10, 20, 30, 40, 50])
print('Vector:', vector)
print('Shape:', vector.shape)
vector.dtype


Vector: [10 20 30 40 50]
Shape: (5,)


dtype('int64')

In [ ]:
vc = np.array(["a", "b"])
print(vc)
print(vc.shape)
print(type(vc))
vc.dtype

['a' 'b']
(2,)
<class 'numpy.ndarray'>


dtype('<U1')

In [ ]:
m = np.array([[1,2,3], [4,5,6]])
print(m)
print(type(m))
print(m.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
# Matrix: A two-dimensional array
matrix = np.array([[10, 20], [30, 40]])
print('Matrix:\n', matrix)
print('Shape:', matrix.shape)


Matrix:
 [[10 20]
 [30 40]]
Shape: (2, 2)


In [ ]:
a = np.array([1, 2, "2", "array"])
print(a)
print(type(a))

['1' '2' '2' 'array']
<class 'numpy.ndarray'>


In [ ]:
t = np.array ([[[1,2,3], [4,5,6]], [[1,4,6], [6,9,0]]] )
print(t)

[[[1 2 3]
  [4 5 6]]

 [[1 4 6]
  [6 9 0]]]


In [ ]:
# Tensor: A multi-dimensional array
tensor = np.array([[[10, 20, 30], [40, 50, 60]], [[100, 200, 300], [400, 500, 600]]])
print('Tensor:\n', tensor)
print('Shape:', tensor.shape)


Tensor:
 [[[ 10  20  30]
  [ 40  50  60]]

 [[100 200 300]
  [400 500 600]]]
Shape: (2, 2, 3)


### Indexing and Slicing

In [ ]:
v =np.array([10,99,100])
# print(v[-3])
# print(v[2])
print(v[1:3])
print(v[-2:])
# print(v[1:2])
# print(len(v))

[ 99 100]
[ 99 100]


In [ ]:

# Indexing and Slicing Vectors
vector = np.array([10, 20, 30, 40, 50])
print('First element:', vector[0])
print('Last element:', vector[-1])
print('Elements from index 1 to 3:', vector[1:4])


First element: 10
Last element: 50
Elements from index 1 to 3: [20 30 40]


In [ ]:
# Indexing and Slicing Matrices
matrix = np.array([[10, 20], [30, 40]])
print(matrix[:, 0])
# print('First row:', matrix[0, 0:])
print('Second column:', matrix[:, 1])


[10 30]
Second column: [20 40]


In [ ]:
# Indexing and Slicing Tensors
tensor = np.array([[[10, 20, 30], [40, 50, 60]], [[100, 200, 300], [400, 500, 600]]])
print('First element of first matrix:', tensor[0,0,0])
print('All elements of first row of tensor at index=0:', tensor[0, 0, :])


First element of first matrix: 10
All elements of first row of tensor at index=0: [10 20 30]


### Generating Data with Built-in Functions

In [ ]:
o = np.ones((2,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z = np.zeros((2,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
i = np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
r = np.random.rand(3, 3)
print(r)

[[0.35532076 0.95745071 0.04386836]
 [0.29367308 0.15279847 0.65096585]
 [0.60816484 0.04801575 0.8802453 ]]


In [ ]:
r = np.random.randint(1,20, size=10)
print(r)

[12  1 14  6 14 12  6  6  8 13]


In [ ]:
ar = np.arange(0, 10, 3)
print(ar)

[0 3 6 9]


In [ ]:
# Generating data using built-in functions
ones = np.ones((3,3))
zeros = np.zeros((3,3))
identity_matrix = np.eye(3)
random_data = np.random.rand(3, 3)
arange_data = np.arange(0, 10, 2)

print('Ones:\n', ones)
print('Zeros:\n', zeros)
print('Identity Matrix:\n', identity_matrix)
# print('Random Data:\n', random_data)
# print('Arange Data:', arange_data)


Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Stacking Data

In [ ]:
# Stacking Data
ones = np.ones((2,2))
zeros = np.zeros((2,2))
# Vertical stack
# vert_stack = np.vstack([ones, zeros])
# print('Vertical Stack:\n', vert_stack)

# Horizontal stack
horiz_stack = np.hstack([ones, zeros])
print('Horizontal Stack:\n', horiz_stack)


Horizontal Stack:
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]]


# Numpy

**np.arange()** creates an array with a sequence of numbers at evenly spaced intervals.
**Syntax: np.arange(start, stop, step)**

In [ ]:
# Creating a sequence of the first 10 whole numbers using arange
arr_seq = np.arange(10)
print("Sequence of first 10 whole numbers:", arr_seq)

# Creating a sequence from 0 to 20 with steps of 3 using arange
arr_steps = np.arange(0, 20, 3)
print("Sequence with steps of 3:", arr_steps)

Sequence of first 10 whole numbers: [0 1 2 3 4 5 6 7 8 9]
Sequence with steps of 3: [ 0  3  6  9 12 15 18]


**np.linspace()** creates an array of evenly spaced numbers between a specified start and stop, and you specify how many values to generate.
**Syntax: np.linspace(start, stop, num)**
In np.linspace(), the stop value is included by default.
Syntax: np.linspace(start, stop, num, endpoint=True)


In [ ]:
# Creating 5 values between 0 and 3 using linspace
arr_linspace = np.linspace(0, 3, 5)
print("Sequence of 5 values between 0 and 3:", arr_linspace)

# arr_linspace = np.linspace(0, 3, 5, endpoint=True)

Sequence of 5 values between 0 and 3: [0.   0.75 1.5  2.25 3.  ]


**np.array() vs np.asarray():**
**np.array():** Creates a new NumPy array from input data. It always returns a copy of the original data, which can be time-consuming for large datasets.
**np.asarray():** Converts the input into an array, but it does not copy the data if the input is already a NumPy array. This makes it faster when handling large arrays.


In [ ]:
# Converting a list into a NumPy array using asarray
list_data = [20, 40, 60, 80]
array_from_list = np.asarray(list_data)
print("Array from list:", array_from_list)

# Converting a tuple into a NumPy array using asarray
tuple_data = (1.2, 3.4, 5.6)
array_from_tuple = np.asarray(tuple_data)
print("Array from tuple:", array_from_tuple)

Array from list: [20 40 60 80]
Array from tuple: [1.2 3.4 5.6]


**np.random.rand():** Generates an array of random numbers from a uniform distribution between 0 and 1.
**np.random.randint():** Generates an array of random integers within a specified range.
**Syntax: np.random.randint(low, high, size)**

In [ ]:
random = np.random.rand(2, 2)  # Output: 2x2 array with random floats between 0 and 1
random_integer = np.random.randint(1, 10, size=(2, 2))  # Output: 2x2 array with random integers between 1 and 10
print(random)
print(random_integer)

[[0.36029516 0.16595904]
 [0.59267072 0.31372963]]
[[1 8]
 [7 7]]


**reshape():** Reshapes the array into a specified shape (e.g., from a 1D array to a 2D array). The number of elements must remain the same.
**Syntax: array.reshape(new_shape)**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2, 3)  # Reshapes into 2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

 **np.empty():** is used to create a new array without initializing its elements to any particular values. It **allocates memory** for the array but**does not set the values of its elements**.

In [ ]:
# Creating an empty array (uninitialized values)
empty_arr = np.empty((2, 2)) # garbage values
print("Empty array (uninitialized):\n", empty_arr)

Empty array (uninitialized):
 [[0.75 1.5 ]
 [2.25 3.  ]]


**.copy()** method creates a new array in a different memory location. Any changes made to the new array will not affect the original array, and vice versa.

**Using =** does not create a new array; it simply creates a new reference (or alias) to the original array. Both variables will point to the same memory location. Any changes made to one will affect the other.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = arr1.copy()  # arr2 is a new array in a different memory location

arr2[0] = 100
print(arr1)  # Output: [1 2 3]  (Original array is unchanged)
print(arr2)  # Output: [100 2 3]  (Only arr2 is modified)

[1 2 3]
[100   2   3]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = arr1  # Both arr1 and arr2 point to the same array

arr2[0] = 100
print(arr1)  # Output: [100 2 3]  (Changes are reflected in arr1)
print(arr2)  # Output: [100 2 3]  (Both are the same)


[100   2   3]
[100   2   3]


**max():** Returns the maximum value in the array.

**max(axis=0):** Returns the maximum value along a specified axis for multidimensional arrays (axis=0 for columns, axis=1 for rows).

**argmax():** Returns the index of the maximum value in the array.



In [ ]:
arr = np.array([1, 5, 3])
print(arr.max())
arr1 = np.array([[1, 5, 3], [7, 2, 9]])
print(arr1.max(axis=0))
arr2 = np.array([[1, 5, 3], [7, 2, 9]])
print(arr2.max(axis=1))
arr3 = np.array([1, 5, 3])
print(arr3.argmax())

5
[7 5 9]
[5 9]
1


**min():** Returns the minimum value in the array.

**argmin():** Returns the index of the minimum value in the array.


In [ ]:
arr = np.array([1, 5, 3])
print(arr.min())
arr1 = np.array([5, 3,1])
print(arr1.argmin())

1
2


**.size:** Returns the total number of elements in the array.

**.ndim:** Returns the number of dimensions (axes) in the array.

**dtype:** stands for data type in NumPy. It is an attribute of a NumPy array that describes the type of elements contained in the array.

**type():** is a built-in Python function that returns the type of an object in Python.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.ndim)  # Output: 2 (2D array)

print(type(arr))
print(arr.dtype)


6
2
<class 'numpy.ndarray'>
int64


# Class Task: From slide 16-19